version: '3'
services:
  # Mysql Database
  mysql:
    container_name: is3107-mysql
    image: mysql:latest
    environment:
      USER_NAME: root
      MYSQL_DATABASE: airflow
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"

  # Airflow webserver
  webserver:
    container_name: is3107-webserver
    build:
      dockerfile: Dockerfile
      context: "./airflowDockerfile"    
    restart: always
    depends_on:
      - mysql
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql://root:root@mysql/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__TIMEOUT: '150s' # Increase the timeout to 120 seconds
      AIRFLOW__WEBSERVER__DAGBAG_IMPORT_TIMEOUT: '90s'
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        airflow db init &&
        airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.com &&
        airflow webserver --port 8080 -D &&
        airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
